// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// C FFI 导出：与 src/rust_ohos_app.c 中的符号保持一致，
/// 确保 ffigen 生成的 Dart 绑定能在鸿蒙等通过 cargokit 编译 Rust 的平台上正常工作。
Future<int> sum({required int a, required int b}) =>
    RustLib.instance.api.crateApiFfiSum(a: a, b: b);

Future<int> sumLongRunning({required int a, required int b}) =>
    RustLib.instance.api.crateApiFfiSumLongRunning(a: a, b: b);
