// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge_ohos/flutter_rust_bridge_ohos_for_generated.dart';

Future<void> hello({required String hello}) =>
    RustLib.instance.api.crateApiHelloHello(hello: hello);
